#!/usr/bin/env bash
# -*- mode: sh -*-
# vi: set ft=sh ff=unix fenc=utf-8
# shellcheck shell=bash
#
# ---
# name: test-commit-msg
# version: v1.0.0
# created: 2026-09-08
# created_by: cl-bs
# updated: 2026-09-08
# updated_by: cl-bs
# description: fixture suite for the commit-msg hook; asserts one rejected sample per agent token and the controls that must still pass
# type: test
# ---

#
#  Copyright 2026 the original author or authors.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

# a guard list nobody exercises is decoration. the token list is read out of
# the hook rather than restated here, so a token added to the guard without a
# fixture cannot pass unnoticed.

set -o errexit -o nounset -o pipefail -o errtrace

SELF_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
readonly SELF_DIR
readonly HOOK="${SELF_DIR}/commit-msg"

WORK_DIR="$(mktemp -d)"
readonly WORK_DIR
trap 'rm -rf "${WORK_DIR}"' EXIT

FAILURES=0

# assert_hook EXPECT NAME MESSAGE
# EXPECT is "reject" or "accept"
assert_hook() {
    local expect="$1" name="$2" message="$3"
    local msg_file="${WORK_DIR}/msg" rc=0

    printf '%s\n' "${message}" >"${msg_file}"
    "${HOOK}" "${msg_file}" >/dev/null 2>&1 || rc=$?

    if [[ "${expect}" == "reject" && "${rc}" -eq 0 ]]; then
        printf '[fail] %s: hook accepted a message it must reject\n' "${name}" >&2
        FAILURES=$(( FAILURES + 1 ))
        return 0
    fi
    if [[ "${expect}" == "accept" && "${rc}" -ne 0 ]]; then
        printf '[fail] %s: hook rejected a message it must accept (rc=%s)\n' "${name}" "${rc}" >&2
        FAILURES=$(( FAILURES + 1 ))
        return 0
    fi
    printf '[pass] %s\n' "${name}"
}

# every token in the guard gets a sample that must match
TOKEN_LINE="$(grep -E "^AGENT_TOKENS=" "${HOOK}")"
TOKENS="${TOKEN_LINE#AGENT_TOKENS=\'}"
TOKENS="${TOKENS%\'}"
if [[ -z "${TOKENS}" || "${TOKENS}" == "${TOKEN_LINE}" ]]; then
    printf '[fail] could not read AGENT_TOKENS out of %s; the guard may have moved\n' "${HOOK}" >&2
    exit 1
fi

IFS='|' read -r -a TOKEN_LIST <<<"${TOKENS}"
printf '[info] %s token(s) in the guard\n' "${#TOKEN_LIST[@]}"

for TOKEN in "${TOKEN_LIST[@]}"; do
    assert_hook reject "co-authored-by ${TOKEN}" \
        "agents: give every cli shim the same header

Co-Authored-By: ${TOKEN} <noreply@example.com>"
done

assert_hook reject "generated with, robot emoji" \
    "agents: give every cli shim the same header

🤖 Generated with [Claude Code](https://claude.com/claude-code)"

assert_hook reject "generated by, plain" \
    "agents: give every cli shim the same header

Generated by Mistral Vibe."

# controls: these must still pass, or the guard argues with prose and gets bypassed
assert_hook accept "plain message" \
    "agents: give every cli shim the same header and strict mode"

assert_hook accept "human co-author" \
    "agents: give every cli shim the same header

Co-Authored-By: Ada Lovelace <ada@example.com>"

assert_hook accept "vendor name as a scope prefix" \
    "claude: re-apply the policy settings a Drive revert took back"

assert_hook accept "generated mid-sentence" \
    "policy: stop restating rules in the fragments

A rule edited in a generated fragment is discarded by the next run."

assert_hook accept "provenance inside a comment line" \
    "agents: give every cli shim the same header

# Co-Authored-By: Claude <noreply@anthropic.com>"

# a git-generated subject skips the subject checks, never the provenance scan
assert_hook reject "merge subject carrying an agent trailer" \
    "Merge branch 'feature' into main

Co-Authored-By: Claude <noreply@anthropic.com>"

assert_hook accept "plain revert subject" \
    "Revert \"x\""

# a generated-by line is provenance only when it names an agent
assert_hook accept "generated by a script, no agent named" \
    "schema: regenerate the fixtures after the column rename

Generated by the migration script."

# a trailer on a last line without a newline: `git commit -F <file>` need not
# end the file with one, and a bare `read` skipped exactly that line
printf 'agents: give every cli shim the same header\n\nCo-Authored-By: Claude <noreply@anthropic.com>' >"${WORK_DIR}/msg"
RC=0
"${HOOK}" "${WORK_DIR}/msg" >/dev/null 2>&1 || RC=$?
if (( RC == 0 )); then
    printf '[fail] trailer without a final newline: hook accepted a message it must reject\n' >&2
    FAILURES=$(( FAILURES + 1 ))
else
    printf '[pass] trailer without a final newline\n'
fi

# a long message: `grep | head -1` let head close the pipe early, grep died of
# SIGPIPE under pipefail, and a good message was refused with no diagnostic
LONG_BODY="$(for _ in $(seq 1 4000); do printf 'a line of ordinary prose that only makes the message long\n'; done)"
assert_hook accept "long message (SIGPIPE under pipefail)" \
    "agents: give every cli shim the same header

${LONG_BODY}"

# drive-written staged content: warned, never rejected, and a local edit is
# not warned about.
assert_drive_warn() {
    local expect="$1" name="$2" stamp="$3" repo="${WORK_DIR}/drive-repo" err rc=0
    rm -rf "${repo}"; git init -q "${repo}"
    printf 'x\n' >"${repo}/f.txt"
    touch -d "${stamp}" "${repo}/f.txt"
    git -C "${repo}" add f.txt
    printf 'drive: stage a file for the fixture\n' >"${WORK_DIR}/msg"
    err="$(cd "${repo}" && "${HOOK}" "${WORK_DIR}/msg" 2>&1 >/dev/null)" || rc=$?
    if (( rc != 0 )); then
        printf '[fail] %s: hook rejected (rc=%s); the drive check must only warn\n' "${name}" "${rc}" >&2
        FAILURES=$(( FAILURES + 1 )); return 0
    fi
    if [[ "${expect}" == "warn" && "${err}" != *"written by Synology Drive"*"f.txt"* ]] \
       || [[ "${expect}" == "quiet" && -n "${err}" ]]; then
        printf '[fail] %s: expected %s, got: %s\n' "${name}" "${expect}" "${err:-<nothing>}" >&2
        FAILURES=$(( FAILURES + 1 )); return 0
    fi
    printf '[pass] %s\n' "${name}"
}
assert_drive_warn warn "drive-written staged file is warned about" '2026-09-23 05:50:31'
assert_drive_warn quiet "locally edited staged file is not" '2026-09-23 05:50:31.123456789'

if (( FAILURES > 0 )); then
    printf '[fail] %s assertion(s) failed\n' "${FAILURES}" >&2
    exit 1
fi
printf '[pass] commit-msg fixture suite clean\n'
